export enum DECLENSIONS {
    Answer = 'answer',
    Comment = 'comment',
    Common = 'common',
    Company = 'company',
    Domain = 'Domain',
    Human = 'human',
    Network = 'network',
    Repost = 'repost',
    Request = 'request',
    Subscriber = 'subscriber',
    Year = 'year',
    Relationship = 'relationship',
    Personal = 'personal',
    Yours = 'yours',
    Chat = 'chat',
    Profile = 'profile',
    Community = 'community',
    Profession = 'profession',
    Group = 'group',
    GroupOf = 'groupOf',
    Vacancies = 'vacancies',
    Views = 'views',
    Strong = 'strong',
    Other = 'other',
}

type DeclensionMap = Record<DECLENSIONS, [string, string, string]>;

export const DECLENSIONS_MAP: DeclensionMap = {
    [DECLENSIONS.Answer]: ['ответ', 'ответа', 'ответов'],
    [DECLENSIONS.Comment]: ['коммент', 'коммента', 'комментов'],
    [DECLENSIONS.Common]: ['общая', 'общие', 'общих'],
    [DECLENSIONS.Company]: ['компанию', 'компании', 'компаний'],
    [DECLENSIONS.Domain]: ['индустрию', 'индустрии', 'индустрий'],
    [DECLENSIONS.Human]: ['человек', 'человека', 'человек'],
    [DECLENSIONS.Network]: ['сетка', 'сетки', 'сеток'],
    [DECLENSIONS.Repost]: ['репост', 'репоста', 'репостов'],
    [DECLENSIONS.Request]: ['заявка', 'заявки', 'заявок'],
    [DECLENSIONS.Subscriber]: ['подписчик', 'подписчика', 'подписчиков'],
    [DECLENSIONS.Year]: ['год', 'года', 'лет'],
    [DECLENSIONS.Relationship]: ['связь', 'связи', 'связей'],
    [DECLENSIONS.Personal]: ['личная', 'личные', 'личных'],
    [DECLENSIONS.Yours]: ['ваша', 'ваши', 'ваших'],
    [DECLENSIONS.Chat]: ['чат', 'чата', 'чатов'],
    [DECLENSIONS.Profile]: ['профиль', 'профиля', 'профилей'],
    [DECLENSIONS.Community]: ['сообщество', 'сообщества', 'сообществ'],
    [DECLENSIONS.Profession]: ['профессию', 'профессии', 'профессий'],
    [DECLENSIONS.Group]: ['группу', 'группы', 'групп'],
    [DECLENSIONS.GroupOf]: ['группы', 'групп', 'групп'],
    [DECLENSIONS.Vacancies]: ['вакансия', 'вакансии', 'вакансий'],
    [DECLENSIONS.Views]: ['просмотр', 'просмотра', 'просмотров'],
    [DECLENSIONS.Strong]: ['сильная', 'сильные', 'сильных'],
    [DECLENSIONS.Other]: ['другая', 'другие', 'других'],
};
