export enum Links {
    CHANNEL = 'CHANNEL',
    POST = 'POST',
    COMMUNITY = 'COMMUNITY',
    PRIVATE_COMMUNITY = 'PRIVATE_COMMUNITY',
    JOIN_COMMUNITY = 'JOIN_COMMUNITY',
    PROFILE = 'PROFILE',
    COMMUNITIES = 'COMMUNITIES',
    CHATS = 'CHATS',
    EDIT_PROFILE = 'EDIT_PROFILE',
    FOLLOW_BACK = 'FOLLOW_BACK',
    FOLLOWERS = 'FOLLOWERS',
    CHANGE_TEST_DOMAIN = 'CHANGE_TEST_DOMAIN',
    AUTH = 'AUTH',
    NETWORKS = 'NETWORKS',
    PROFILE_VIEWS = 'PROFILE_VIEWS',
    CREATE_POST = 'CREATE_POST',
    FEED = 'FEED',
}

export const DOMAIN_NAME_SHORTENED_LINKS = 'set.ki';

export const YANDEX_DEEP_LINK_DOMAIN = '4284841.redirect.appmetrica.yandex.com';

export const AVAILABLE_URLS = ['setka.work', 'setka.ru', 'setka.so', YANDEX_DEEP_LINK_DOMAIN];
