export enum EventTypes {
    NEW_P2P_CHANNEL_CREATED = 'NEW_P2P_CHANNEL_CREATED',
    NEW_P2P_MESSAGE = 'NEW_P2P_MESSAGE',
    NEW_POST_COMMENT = 'NEW_POST_COMMENT',
    NEW_NOTIFICATION = 'NEW_NOTIFICATION',
    P2P_READ_BY_OPPONENT = 'P2P_READ_BY_OPPONENT',
}
